/* eslint-disable react-refresh/only-export-components */
import {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  BarChart3,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Coins,
  Command,
  Copy,
  Download,
  Droplet,
  Edit3,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Gauge,
  Home,
  Info,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LineChart,
  Link as LinkIcon,
  Loader2,
  type LucideIcon,
  Minus,
  Moon,
  MoreHorizontal,
  Pencil,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Repeat,
  Save,
  Search,
  Settings,
  Shield,
  ShowerHead,
  Sun,
  Thermometer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  Users,
  Wallet,
  Wrench,
  X,
} from "lucide-react";
import type { ModulKey } from "./moduleAccent";

/** Mapping ModulKey → Lucide-Icon. Dashboard/Datenschutz/Einstellungen sind nicht in ModulKey enthalten. */
export const ModulIcons: Record<
  ModulKey | "dashboard" | "datenschutz" | "einstellungen",
  LucideIcon
> = {
  dashboard: LayoutDashboard,
  mieter: Users,
  zaehler: Gauge,
  wasser: Droplet,
  nebenkosten: Receipt,
  finanzen: Wallet,
  rendite: TrendingUp,
  instandhaltung: Wrench,
  uebergabe: KeyRound,
  einstellungen: Settings,
  datenschutz: Shield,
};

export type ModulIconKey = keyof typeof ModulIcons;

/** Convenience-Wrapper für ein Modul-Icon mit konsistenten Defaults (strokeWidth 1.75). */
export function ModulIcon({
  modul,
  className,
  size = 16,
}: {
  modul: ModulIconKey;
  className?: string;
  size?: number;
}) {
  const Icon = ModulIcons[modul];
  return <Icon size={size} strokeWidth={1.75} className={className} aria-hidden="true" />;
}

/** Status-Icons für Toast/Alert/Inline-Status. */
export const StatusIcons = {
  success: CheckCircle2,
  error: AlertCircle,
  warning: AlertTriangle,
  info: Info,
} as const;

export type { LucideIcon };

export {
  AlertCircle,
  AlertTriangle,
  ArrowRight,
  BarChart3,
  Building2,
  Calendar,
  Check,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ClipboardList,
  Clock,
  Coins,
  Command,
  Copy,
  Download,
  Droplet,
  Edit3,
  Euro,
  ExternalLink,
  Eye,
  EyeOff,
  FileText,
  Filter,
  Gauge,
  Home,
  Info,
  KeyRound,
  Landmark,
  LayoutDashboard,
  LineChart,
  LinkIcon,
  Loader2,
  Minus,
  Moon,
  MoreHorizontal,
  Pencil,
  Plus,
  Printer,
  Receipt,
  RefreshCw,
  Repeat,
  Save,
  Search,
  Settings,
  Shield,
  ShowerHead,
  Sun,
  Thermometer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Upload,
  Users,
  Wallet,
  Wrench,
  X,
};
