/* eslint-disable react-refresh/only-export-components */
import {
  LayoutDashboard,
  Users,
  Gauge,
  Droplet,
  Receipt,
  Wallet,
  TrendingUp,
  TrendingDown,
  Wrench,
  KeyRound,
  Settings,
  Shield,
  FileText,
  Home,
  Building2,
  Plus,
  Search,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ArrowRight,
  Check,
  X,
  AlertTriangle,
  AlertCircle,
  Info,
  CheckCircle2,
  MoreHorizontal,
  Download,
  Upload,
  Edit3,
  Trash2,
  Calendar,
  Clock,
  Filter,
  Sun,
  Moon,
  Euro,
  Printer,
  Eye,
  EyeOff,
  RefreshCw,
  Loader2,
  Pencil,
  Save,
  Copy,
  Link as LinkIcon,
  ExternalLink,
  Command,
  Minus,
  BarChart3,
  LineChart,
  Thermometer,
  ShowerHead,
  Repeat,
  Coins,
  Landmark,
  ClipboardList,
  type LucideIcon,
} from 'lucide-react';
import type { ModulKey } from './moduleAccent';

/** Mapping ModulKey → Lucide-Icon. Dashboard/Datenschutz/Einstellungen sind nicht in ModulKey enthalten. */
export const ModulIcons: Record<
  ModulKey | 'dashboard' | 'datenschutz' | 'einstellungen',
  LucideIcon
> = {
  dashboard: LayoutDashboard,
  mieter: Users,
  zaehler: Gauge,
  wasser: Droplet,
  nebenkosten: Receipt,
  finanzen: Wallet,
  rendite: TrendingUp,
  instandhaltung: Wrench,
  uebergabe: KeyRound,
  einstellungen: Settings,
  datenschutz: Shield,
};

export type ModulIconKey = keyof typeof ModulIcons;

/** Convenience-Wrapper für ein Modul-Icon mit konsistenten Defaults (strokeWidth 1.75). */
export function ModulIcon({
  modul,
  className,
  size = 16,
}: {
  modul: ModulIconKey;
  className?: string;
  size?: number;
}) {
  const Icon = ModulIcons[modul];
  return <Icon size={size} strokeWidth={1.75} className={className} aria-hidden="true" />;
}

/** Status-Icons für Toast/Alert/Inline-Status. */
export const StatusIcons = {
  success: CheckCircle2,
  error: AlertCircle,
  warning: AlertTriangle,
  info: Info,
} as const;

export type {
  LucideIcon,
};

export {
  Plus,
  Search,
  ChevronRight,
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ArrowRight,
  Check,
  X,
  AlertTriangle,
  AlertCircle,
  Info,
  CheckCircle2,
  MoreHorizontal,
  Download,
  Upload,
  Edit3,
  Trash2,
  Calendar,
  Clock,
  Filter,
  Sun,
  Moon,
  Building2,
  Home,
  Euro,
  Printer,
  Eye,
  EyeOff,
  RefreshCw,
  Loader2,
  Pencil,
  Save,
  Copy,
  LinkIcon,
  ExternalLink,
  Command,
  Minus,
  TrendingUp,
  TrendingDown,
  BarChart3,
  LineChart,
  Thermometer,
  ShowerHead,
  Repeat,
  Coins,
  Landmark,
  ClipboardList,
  FileText,
  Users,
  Gauge,
  Droplet,
  Receipt,
  Wallet,
  Wrench,
  KeyRound,
  Settings,
  Shield,
  LayoutDashboard,
};
